require:
  - solidus_dev_support/rubocop

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Rails/Output:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
