language: ruby
rvm:
  - 2.5.0
install:
  - bundle install --path vendor/bundle
script:
  - bundle exec rake test_app
  - bundle exec rspec spec/
env:
  matrix:
    - SOLIDUS_BRANCH=v2.0
    - SOLIDUS_BRANCH=v2.1
    - SOLIDUS_BRANCH=v2.2
    - SOLIDUS_BRANCH=v2.3
    - SOLIDUS_BRANCH=v2.4
    - SOLIDUS_BRANCH=v2.5
    - SOLIDUS_BRANCH=v2.6
    - SOLIDUS_BRANCH=v2.7
    - SOLIDUS_BRANCH=master
